name: jax
channels:
  - conda-forge
  - nvidia
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy
  - matplotlib
  - tqdm
  - pip:
    - jax[cuda12]
    - flax
    - optax
    - orbax-checkpoint
    - tensorflow-datasets
    - tensorflow-cpu  # Only CPU TF needed for tfds
    - ml_collections
    - absl-py
    - wandb
